export const vaultAbi = [
  {
    type: 'function',
    name: 'asset',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalAssets',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'convertToShares',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'convertToAssets',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewDeposit',
    inputs: [{ name: 'assets', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewMint',
    inputs: [{ name: 'shares', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'basketLength',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'basketTokens',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenPriceFeedId',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'redemptionFeeBps',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'managementFeeBps',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // Deposit/mint with Pyth
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'pythUpdateData', type: 'bytes[]' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'pythUpdateData', type: 'bytes[]' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'depositWithPermit',
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'pythUpdateData', type: 'bytes[]' },
      { name: 'deadline', type: 'uint256' },
      { name: 'v', type: 'uint8' },
      { name: 'r', type: 'bytes32' },
      { name: 's', type: 'bytes32' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'mintWithPermit',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'pythUpdateData', type: 'bytes[]' },
      { name: 'deadline', type: 'uint256' },
      { name: 'v', type: 'uint8' },
      { name: 'r', type: 'bytes32' },
      { name: 's', type: 'bytes32' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  // Redeem
  {
    type: 'function',
    name: 'redeemInKind',
    inputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner_', type: 'address' },
      { name: 'pythUpdateData', type: 'bytes[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  // batchExecute (rebalance)
  {
    type: 'function',
    name: 'batchExecute',
    inputs: [
      { name: 'targets', type: 'address[]' },
      { name: 'values', type: 'uint256[]' },
      { name: 'data', type: 'bytes[]' },
      { name: 'tokensIn', type: 'address[]' },
      {
        name: 'outputCheck',
        type: 'tuple',
        components: [
          { name: 'tokensOut', type: 'address[]' },
          { name: 'expectedAmountsOut', type: 'uint256[]' },
          { name: 'slippageBps', type: 'uint256' },
        ],
      },
      { name: 'pythUpdateData', type: 'bytes[]' },
    ],
    outputs: [{ type: 'bytes[]' }],
    stateMutability: 'payable',
  },
  // Custom errors
  { type: 'error', name: 'VaultPaused', inputs: [] },
  { type: 'error', name: 'VaultNotPaused', inputs: [] },
  { type: 'error', name: 'UserDepositCapExceeded', inputs: [] },
  { type: 'error', name: 'FeeTooHigh', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'SlippageExceeded', inputs: [] },
  { type: 'error', name: 'PythOracleNotSet', inputs: [] },
  { type: 'error', name: 'InvalidBasketLength', inputs: [] },
  { type: 'error', name: 'InvalidWeightsSum', inputs: [] },
  { type: 'error', name: 'RestrictedTokenCall', inputs: [] },
  { type: 'error', name: 'ArrayLengthMismatch', inputs: [] },
  { type: 'error', name: 'BasketTooLarge', inputs: [] },
  { type: 'error', name: 'StalePrices', inputs: [] },
  { type: 'error', name: 'MissingFeedId', inputs: [] },
  { type: 'error', name: 'PythUpdateRequired', inputs: [] },
  { type: 'error', name: 'DepositMoreThanMax', inputs: [] },
  { type: 'error', name: 'WithdrawMoreThanMax', inputs: [] },
  { type: 'error', name: 'RedeemMoreThanMax', inputs: [] },
  { type: 'error', name: 'InsufficientBalance', inputs: [] },
  { type: 'error', name: 'InsufficientAllowance', inputs: [] },
  { type: 'error', name: 'InvalidPermit', inputs: [] },
  { type: 'error', name: 'PermitExpired', inputs: [] },
] as const
