export const REVERT_MESSAGES: Record<string, string> = {
  VaultPaused: 'This vault is currently paused. Deposits are disabled.',
  UserDepositCapExceeded: 'Deposit exceeds your per-user limit.',
  VaultNotPaused: 'Vault must be paused for this action.',
  FeeTooHigh: 'Fee exceeds the maximum allowed (5%).',
  ZeroAddress: 'Invalid address provided.',
  SlippageExceeded: 'Slippage tolerance exceeded. Try again.',
  PythOracleNotSet: 'Price oracle is not configured.',
  InvalidBasketLength: 'Invalid basket configuration.',
  InvalidWeightsSum: 'Basket weights must sum to 10,000.',
  RestrictedTokenCall: 'Restricted token operation.',
  ArrayLengthMismatch: 'Array length mismatch.',
  BasketTooLarge: 'Basket exceeds maximum token count.',
  PointsTimestampInFuture: 'Timestamp cannot be in the future.',
  PointsTimestampBeforeDeployment: 'Timestamp cannot be before deployment.',
  DeployedAtAlreadySet: 'Deployment timestamp is already set.',
  StalePrices: 'Token prices are stale. Please try again in a moment.',
  MissingFeedId: 'Missing Pyth price feed for a basket token.',
  PythUpdateRequired: 'Price update is required for this operation.',
  DepositMoreThanMax: 'Deposit exceeds the maximum allowed.',
  WithdrawMoreThanMax: 'Withdrawal exceeds the maximum allowed.',
  RedeemMoreThanMax: 'Redemption exceeds your share balance.',
  InsufficientBalance: 'Insufficient token balance.',
  InsufficientAllowance: 'Insufficient token allowance. Please approve first.',
  AllowanceOverflow: 'Allowance overflow.',
  InvalidPermit: 'Invalid permit signature.',
  PermitExpired: 'Permit signature has expired.',
}
